### ISSUE TITLE
Forklift not appearing in visualizer

### ISSUE THREAD

**Issue by sparr1** [MAPLE-Robot-Subgoaling/forklift#6]
I think it has something to do with some image transformation you're trying. Is there a stable workaround for me to comment out certain lines and get back the old stuff while you're working on this?

**Comment by khalil8500** [comment]
did you pull the code because it is working on mine. Including the reverse.

**Comment by sparr1** [comment]
And github is fully up to date with what you have? run git status

**Comment by khalil8500** [comment]
yeah I'm about to push after some changes. This is working on mine so try pulling what I push and test it.

**Comment by sparr1** [comment]
It's not working for me still. Not really sure why.

**Comment by khalil8500** [comment]
hmm check the pushed code in the visualizer and your code. Did you change anything after what I had pushed before?

**Comment by sparr1** [comment]
no

**Comment by sparr1** [comment]
Do you use rx or ry at all in your visualizer code? looks extraneous in mine

**Comment by khalil8500** [comment]
no, you can remove them

**Comment by sparr1** [comment]
Can you tell me what version your JRE says it is to the right of it in package explorer? Should be the same as mine, J2SE-1.5

**Comment by khalil8500** [comment]
Yeah, that's the same on both of my computers. I tried on my laptop and desktop and they both worked.

**Comment by sparr1** [comment]
Both windows machines?

**Comment by khalil8500** [comment]
yeah the os is the only thing that is different between your's and my computers

**Comment by khalil8500** [comment]
when you run it, print out the rectangle's width and height in the agent painter

**Comment by khalil8500** [comment]
and try printing out other values in that transformation. I want to compare my values to yours

**Comment by sparr1** [comment]
Alright

**Comment by sparr1** [comment]
Actually, just push the printlines you'll use

**Comment by khalil8500** [comment]
already did lol

**Comment by sparr1** [comment]
Haha yeah. It suddenly works now. Not really sure why the printline update was what did it. Will closely analyze the commits to attempt to figure out what it was that was throwing my setup off.

**Comment by khalil8500** [comment]
Haha interesting, the print line were literally the only changes but there are still some minor fixes I need to make like with collisions.
